### ISSUE TITLE
Request: allow for 3 channels on input shape (for RGB images)

### ISSUE THREAD

**Issue by jamesbraza** [zimonitrome/convolution-shape-calculator#8]
I like the [calculator](https://zimonitrome.github.io/convolution-shape-calculator/)!

A common convolution input is RGB images (3 color channels).  It would be cool to have the calculator's `input.shape` allow for 3 channels.  Cheers!

**Comment by zimonitrome** [comment]
You can input custom numbers in the fields! Only the sliders move by square numbers.

Maybe this is not what you mean?  And maybe this can be made more clear in the UI somehow.

**Comment by jamesbraza** [comment]
Ah I see that now, yeah I was just moving the slider (which doesn't index to 3, as you said).

The up/down arrows on the number only show up if you move the mouse over the number, which I didn't think to try.  I see that's an option now, or typing in the number.

I do agree the UI could make this more obvious, regardless, feel free to close this out 👍
